# Exploratory Data Analysis On Wine Quality With Numpy


## Import Numpy


In [2]:
import numpy as np

## Import Dataset

In [4]:
# import wine dataset into numpy
wines = np.genfromtxt('./WineQT.csv',
                      comments="A wine quality dataset",
                      delimiter=",",
                      skip_header=1,
                      dtype=np.int32)


## Understand The Data

In [36]:
print("The shape of the wine dataset is:",wines.shape)
print("The dimension of the wine dataset is:",wines.ndim)

The shape of the wine dataset is: (1143, 13)
The dimension of the wine dataset is: 2


## Return The First 10 Rows Of The Dataset



In [17]:
#display the first 10 rows
first_ten_rows = wines[0:11]
print ("Display: \n)", first_ten_rows)


Display: 
) [[ 7  0  0  1  0 11 34  0  3  0  9  5  0]
 [ 7  0  0  2  0 25 67  0  3  0  9  5  1]
 [ 7  0  0  2  0 15 54  0  3  0  9  5  2]
 [11  0  0  1  0 17 60  0  3  0  9  6  3]
 [ 7  0  0  1  0 11 34  0  3  0  9  5  4]
 [ 7  0  0  1  0 13 40  0  3  0  9  5  5]
 [ 7  0  0  1  0 15 59  0  3  0  9  5  6]
 [ 7  0  0  1  0 15 21  0  3  0 10  7  7]
 [ 7  0  0  2  0  9 18  0  3  0  9  7  8]
 [ 6  0  0  1  0 15 65  0  3  0  9  5 10]
 [ 5  0  0  1  0 16 59  0  3  0  9  5 12]]


## Return The 12th Column Of The Dataset

In [18]:
#Display the 12th column
twelveth_column = wines[:,11] 
print("Display:\n", twelveth_column)

Display:
 [5 5 5 ... 5 6 5]


## The Sum of all the Elements Between Column 1 to 10

In [21]:
one_to_ten_col = wines[:,1:11].sum()
print ("summation:", one_to_ten_col)

summation: 87680


## Mean Of The Array

In [23]:
mean_of_wines =wines.mean()
print("Mean value:", mean_of_wines)

Mean value: 68.86163268053032


## Standard Deviation of the Array

In [24]:
std_dev =wines.std()
print('standard Deviation:',std_dev)

standard Deviation: 248.87134655790663


## Minimum Value Of The Array

In [25]:
min_value = wines.min()
print("Minimium value:", min_value)

Minimium value: 0


## Maximum  Value Of The Array

In [26]:
max_value = wines.max()
print("Maximum value:", max_value)

Maximum value: 1597


## Where the Quality of Wine is Higher Than 5

In [31]:
quality_rating_col = wines[:,-2] #boolarray
quality_rating_greater_than_5 = quality_rating_col > 5
display = quality_rating_col[quality_rating_greater_than_5]
print("Original column:",quality_rating_col)
print("Quality greater than 5:",display)
#find the total numbers of quality rating greater than 5
print("Total Numbers",display.size)

Original column: [5 5 5 ... 5 6 5]
Quality greater than 5: [6 7 7 7 6 6 6 6 6 7 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 7 6 7 7 6 6 6 6 6 6 6 7 6 6 6 6 6 6 7 7 6 6 6 6 7 8 6 6 6 6 6 6
 8 7 6 7 7 6 6 7 7 6 6 6 6 6 6 6 6 6 7 6 6 6 7 6 7 7 6 7 6 6 6 6 6 6 6 6 7
 7 6 6 7 7 7 6 6 6 7 6 6 6 8 6 7 6 6 6 6 7 6 7 6 6 7 7 7 6 6 6 7 6 6 6 8 7
 7 6 6 6 6 7 8 6 6 6 6 6 6 6 6 6 8 6 6 7 7 6 6 8 6 8 6 6 7 7 7 7 7 6 7 6 6
 7 7 6 6 6 6 6 6 6 6 7 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 7 8 6 6 6 6 6 6
 6 6 6 6 6 6 6 7 6 6 7 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 6 6 6 6 6 6 6 7 6 7 6 6 7 6 6 6 7 7 6 7 7 7 6 6 6 6 6 7 7 7 6
 6 6 6 6 6 6 6 6 7 6 7 7 7 7 6 6 6 6 6 6 6 6 6 6 7 6 7 6 6 7 7 7 7 7 7 7 7
 7 7 6 7 6 6 6 6 7 7 6 6 6 6 6 6 6 6 7 7 7 7 7 7 6 6 6 7 6 6 6 6 7 6 6 7 6
 7 7 7 6 6 6 6 6 6 6 7 6 7 7 7 6 8 6 6 6 6 7 7 7 6 6 7 7 6 6 7 6 7 7 8 6 6
 7 6 6 6 6 6 6 7 6 6 7 6 6 6 6 6 6 8 6 7 6 6 7 7 7 6 6 6 6 6 6 6 6 6 7 6 6
 6 6 7 7 7 7 6 6 6 6 6 6 6 6 6 7 6 6 6 6 

## Where the Quality of Wine is Equal to 10

In [38]:
def send_message(data):
    if len(data) == 0:
        print("No wine quality found")
    else:
        print(f"The total of {len(data)}quality rating is found greater than 10")
    

quality_rating_col = wines[:,-2]#Original column
quality_rating_equal_10 = quality_rating_col == 10 #boolean array
display = quality_rating_col[quality_rating_equal_10]

print("Original column:", quality_rating_col)
print("quality greater than 5:",display)

#call function
send_message(display)

Original column: [5 5 5 ... 5 6 5]
quality greater than 5: []
No wine quality found


## Find where the quality rating is greater than 5 and the alcohol rating is greater than 7

In [9]:
quality_greater_than_5_and_alcohol_greater_than_7 = (wines [:,-2] > 5) & (wines [:,-3] > 7)
wines[quality_greater_than_5_and_alcohol_greater_than_7]

array([[  11,    0,    0, ...,    9,    6,    3],
       [   7,    0,    0, ...,   10,    7,    7],
       [   7,    0,    0, ...,    9,    7,    8],
       ...,
       [   6,    0,    0, ...,   11,    6, 1592],
       [   6,    0,    0, ...,    9,    6, 1593],
       [   5,    0,    0, ...,   11,    6, 1595]])